### ISSUE TITLE
Simplify creating a new provider from boilerplate

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-tf-provider-boilerplate#100]
Creating a new provider from the boilerplate requires a good deal of manual find-and-replace. Either #86 or another method should be considered to make it easier to start a repository from scratch, e.g., to not assume the GitHub org is "pulumi" or the NPM scope is "@pulumi".

**Comment by iwahbe** [comment]
Issues that would have been fixed:
- https://github.com/pulumi/pulumi-tf-provider-boilerplate/issues/113

**Comment by danielrbradley** [comment]
This has been completed in https://github.com/pulumi/pulumi-tf-provider-boilerplate/pull/135 which introduces a new `setup.sh` script which does more of the heavy lifting with the replacements.

This will likely be improved further as we extend the integration testing via #137
