### ISSUE TITLE
make tfgen failing to build provider

### ISSUE THREAD

**Issue by jcgsville** [pulumi/pulumi-tf-provider-boilerplate#109]
### What happened?

Trying to create a bridged terraform provider for the neon terraform provider

https://github.com/kislerdm/terraform-provider-neon

I pushed my latest changes here

https://github.com/jcgsville/pulumi-neon

I got to the `make tfgen` step, and I'm getting the following error

```
make tfgen
[ -x /Users/chandler/.pulumi/bin/pulumi ] || curl -fsSL https://get.pulumi.com | sh
pulumi plugin install resource random 4.3.1
(cd provider && go build -o /Users/chandler/Documents/proqure/pulumi-neon/bin/pulumi-tfgen-neon -ldflags "-X github.com/jcsgville/pulumi-neon/provider/pkg/version.Version=0.0.1-alpha.1708194561+1c9af2e1" github.com/jcsgville/pulumi-neon/provider/cmd/pulumi-tfgen-neon)
no required module provides package github.com/jcsgville/pulumi-neon/provider/cmd/pulumi-tfgen-neon; to add it:
	go get github.com/jcsgville/pulumi-neon/provider/cmd/pulumi-tfgen-neon
make: *** [tfgen] Error 1
```

I'm new to Go, so I'm not really sure why I'd have to add the package if the build comment is saying we should try and build that package.

I went through and double checked that I wasn't missing a step in the instructions, though it is of course possible that I did :)

Any suggestions on what might be missing here?

### Example

Clone https://github.com/jcgsville/pulumi-neon

Install go 1.22.0

Run `make tfgen`

### Output of `pulumi about`

pulumi about
CLI
Version      3.106.0
Go Version   go1.22.0
Go Compiler  gc

Host
OS       darwin
Version  14.2.1
Arch     x86_64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/jcgsville
User           jcgsville
Organizations  jcgsville
Token type     personal

Pulumi locates its logs in /var/folders/tb/s29lmjpd7flf9j_np73yhcd80000gn/T/ by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from /Users/chandler/Documents/proqure/pulumi-neon/provider). If you have not created a project yet, use `pulumi new` to do so: no project file found
warning: Failed to get information about the current stack: no Pulumi.yaml project file found (searching upwards from /Users/chandler/Documents/proqure/pulumi-neon/provider). If you have not created a project yet, use `pulumi new` to do so: no project file found

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jcgsville** [comment]
I modified the go build command to

```
go build -o /Users/chandler/Documents/proqure/pulumi-neon/bin/pulumi-tfgen-neon -ldflags "-X github.com/jcsgville/pulumi-neon/provider/pkg/version.Version=0.0.1-alpha.1708194561+1c9af2e1" ./cmd/pulumi-tfgen-neon
```

And got a different error, so that's probably a good sign

```
package github.com/jcgsville/pulumi-neon/provider/cmd/pulumi-tfgen-neon
	imports github.com/jcgsville/pulumi-neon/provider
	resources.go:32:2: use of internal package github.com/kislerdm/terraform-provider-neon/internal/provider not allowed
```

**Comment by iwahbe** [comment]
Hey @jcgsville. I looked into this and I think I found your problem. You misspelled `ORG` in the Makefile. I recommend making this change:

```patch
 Makefile | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/Makefile b/Makefile
index 2ffc9cb..32ea4b9 100644
--- a/Makefile
+++ b/Makefile
@@ -2,7 +2,7 @@ PROJECT_NAME := neon Package
 
 SHELL            := /bin/bash
 PACK             := neon
-ORG              := jcsgville
+ORG              := jcgsville
 PROJECT          := github.com/${ORG}/pulumi-${PACK}
 NODE_MODULE_NAME := ${PACK}
 TF_NAME          := ${PACK}
@@ -48,7 +48,7 @@ build:: install_plugins provider build_sdks install_sdks
 only_build:: build
 
 tfgen:: install_plugins
-	(cd provider && go build -o $(WORKING_DIR)/bin/${TFGEN} -ldflags "-X ${PROJECT}/${VERSION_PATH}=${VERSION}" ${WORKING_DIR}/${PROVIDER_PATH}/cmd/${TFGEN})
+	(cd provider && go build -o $(WORKING_DIR)/bin/${TFGEN} -ldflags "-X ${PROJECT}/${VERSION_PATH}=${VERSION}" ${PROJECT}/${PROVIDER_PATH}/cmd/${TFGEN})
 	$(WORKING_DIR)/bin/${TFGEN} schema --out provider/cmd/${PROVIDER}
 	(cd provider && VERSION=$(VERSION) go generate cmd/${PROVIDER}/main.go)
 

```

**Comment by jcgsville** [comment]
@iwahbe thanks for taking a look so quickly. Apologies that it was just a typo 🤦 I'll make that change and report back

**Comment by jcgsville** [comment]
It worked, btw :) Thanks again
