### ISSUE TITLE
Cannot build tfgen for Pulumi provider for Dynatrace 

### ISSUE THREAD

**Issue by stasialej** [pulumi/pulumi-tf-provider-boilerplate#113]
This is my repo pulumi-dynatrace https://github.com/stasialej/pulumi-dynatrace

when trying to run command make tfgen this error shows up: 
Already replaced ORG name correctly and all the modules and references to Dynatrace provider look ok. 

```

alejandra.stasi@mbpdealejandra pulumi-dynatrace % make tfgen
[ -x /usr/local/bin/pulumi ] || curl -fsSL https://get.pulumi.com | sh
pulumi plugin install resource random 4.3.1
(cd provider && go build -o /Users/alejandra.stasi/Documents/Github/boilerplate/pulumi-dynatrace/bin/pulumi-tfgen-dynatrace -ldflags "-X github.com/stasialej/pulumi-dynatrace/provider/pkg/version.Version=0.0.1-alpha.1712321090+fcf2912c.dirty" github.com/stasialej/pulumi-dynatrace/provider/cmd/pulumi-tfgen-dynatrace)
# github.com/stasialej/pulumi-dynatrace/provider
./resources.go:61:41: undefined: dynatrace.New
make: *** [tfgen] Error 1

```

**Comment by ivanalmendros** [comment]
Same issue for me, I'm also getting stuck on the same step... For some reason this `make tfgen` is not able to get the .New method from Dynatrace.
I checked the previous Pulumi provider that we were using and I saw that the way the provider is created [here](https://github.com/lbrlabs/pulumi-dynatrace/blob/main/provider/resources.go#L93) is different to the current code in the [tf-boilerplate](https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/main/provider/resources.go#L61). Couldn't find the way to fix it, though...
Any support on this would be much appreciated, since the previous provider that we were using is no longer maintained and is out of date with the dynatrace terraform provider, causing clashes and misalignment in some resource models.

Thank you

**Comment by iwahbe** [comment]
Hey @stasialej. I'm sorry it took so long to get back to you. It looks like terraform-provider-dynatrace calls their function [`Provider`](https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/e6631928035202c1474779e4b67ba695f59ef91d/provider/provider.go#L95). https://github.com/stasialej/pulumi-dynatrace compiles with this change:

```patch
 provider/resources.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/provider/resources.go b/provider/resources.go
index fcd65ee..7df0b03 100644
--- a/provider/resources.go
+++ b/provider/resources.go
@@ -58,7 +58,7 @@ func Provider() tfbridge.ProviderInfo {
 	// Create a Pulumi provider mapping
 	prov := tfbridge.ProviderInfo{
 		// Instantiate the Terraform provider
-		P:       shimv2.NewProvider(dynatrace.New(version.Version)()),
+		P:       shimv2.NewProvider(dynatrace.Provider()),
 		Name:    "dynatrace",
 		Version: version.Version,
 		// DisplayName is a way to be able to change the casing of the provider
```

This is the same change that @ivanalmendros found. If you make that edit to `resources.go`, you will get a working provider.

**Comment by iwahbe** [comment]
To get working docs, I would also recommend this change:

```patch
 provider/resources.go | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/provider/resources.go b/provider/resources.go
index fcd65ee..c69040b 100644
--- a/provider/resources.go
+++ b/provider/resources.go
@@ -89,9 +89,9 @@ func Provider() tfbridge.ProviderInfo {
 		Repository: "https://github.com/pulumi/pulumi-dynatrace",
 		// The GitHub Org for the provider - defaults to `terraform-providers`. Note that this
 		// should match the TF provider module's require directive, not any replace directives.
-		GitHubOrg:    "",
+		GitHubOrg:    "dynatrace-oss",
 		MetadataInfo: tfbridge.NewProviderMetadata(metadata),
-		Config: map[string]*tfbridge.SchemaInfo{
+		Config:       map[string]*tfbridge.SchemaInfo{
 			// Add any required configuration here, or remove the example below if
 			// no additional points are required.
 			// "region": {
```

This way the bridge knows where to find the upstream provider's docs.
