### ISSUE TITLE
Release workflow does not build SDKs

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-tf-provider-boilerplate#124]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently release.yml does not seem to build language SDK GitHub Action artifacts that the publish action assumes, therefore it fails. Coming from a question from the 1password provider setup.

Specifically this:

https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/main/deployment-templates/release.yml#L57

Will fail because there are no SDKs build.

The community cookie-cutter templates seem to handle this better: https://github.com/pulumi/pulumi-tf-provider-boilerplate/issues/86

For the moment  consider using those or copying release.yml steps from a pulumi provider such as pulumi/pulumi-random.

**Comment by danielrbradley** [comment]
This has now been resolved by https://github.com/pulumi/pulumi-tf-provider-boilerplate/pull/135 which replaced all the SDK builds with a more standard approach that matches our other providers.
