### ISSUE TITLE
Debugging terraform provider

### ISSUE THREAD

**Issue by smartinellimarco** [pulumi/pulumi-tf-provider-boilerplate#126]
## Issue details

I was wondering if there is a way to trigger a breakpoint inside the bridged terraform provider.

This would be useful to test it using Pulumi code, which is easier to write.

I already tried running the binary with delve, and pointing the Pulumi CLI with PULUMI_DEBUG_PROVIDERS="azure-native:<pid>" pulumi up without success.

edit:

I'm not sure, but if these are separate processes, is there a way to use or point the shimmed provider to a terraform provider instance running in debug mode?

**Comment by guineveresaenger** [comment]
Hi @smartinellimarco - this does already exist!
We recommend following these steps: https://www.pulumi.com/docs/using-pulumi/pulumi-packages/debugging-provider-packages/

Hope that helps you out!

**Comment by smartinellimarco** [comment]
I think I did not explain myself correctly. What I'm trying to do is to debug my Terraform provider (built with SDKv2) with delve, while testing it with a Pulumi project:

<img width="575" alt="Screenshot 2024-06-20 at 17 03 13" src="https://github.com/pulumi/pulumi-tf-provider-boilerplate/assets/15314838/bc96c817-2e29-4b39-94f9-2b263f996144">

I already tried setting breakpoints inside it but they are not triggering

**Comment by smartinellimarco** [comment]
@guineveresaenger Do you mind re-opening the issue until is solved?
