### ISSUE TITLE
Support for custom plugin hosting

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-tf-provider-boilerplate#13]
It is now possible for 3rd parties to publish their own packages - both to NPM/PyPI as well as the hosting plugins in custom storage (see https://github.com/pulumi/pulumi/pull/2789).

We should update the boilerplate to support the end-to-end workflow for setting this up for a new provider that will not be hosted in the Pulumi org.

I expect this includes:
- [ ] Putting the right info in the packages to trigger `pulumi plugin install --server ...`
- [ ] Publishing GitHub releases or other binary publishing from CI and using that target location as the embedded server location.

**Comment by fernandocarletti** [comment]
Currently is is possible to use the Github Releases to retrieve the compiled binary, with a tiny workaround, assuming the package follows the naming standard in use (e.g.: `pulumi-resource-foo-v0.0.0-darwin-amd64.tar.gz`):
`pulumi plugin install --server https://github.com/foo/pulumi-bar/releases/download/v0.0.0 resource bar v0.0.0`

Maybe it would be great to have an option to simplify using GH as a source:
`pulumi plugin install --github foo/pulumi-bar bar v0.0.0`, WDYT?

**Comment by clstokes** [comment]
Once this is complete a guide or blog post that walks a user through setting this up (i.e. with GitHub releases) would be great!

**Comment by stack72** [comment]
Closing this out now that we have support for `PluginDownloadURL` :)
