### ISSUE TITLE
`.golangci.yml ` contains deprected linters and configuration options.

### ISSUE THREAD

**Issue by heyzling** [pulumi/pulumi-tf-provider-boilerplate#130]
### What happened?

`.golangci.yml ` contains deprecated linters and configuration options.

### Example

```shell
$ make lint_provider
... ...
WARN [config_reader] The configuration option `run.skip-files` is deprecated, please use `issues.exclude-files`. 
WARN [lintersdb] The linter named "megacheck" is deprecated. It has been split into: gosimple, staticcheck, unused.
```

### Output of `pulumi about`

-

### Additional context

```shell
$ go version
go version go1.22.5 linux/amd64

$ golangci-lint version
golangci-lint has version 1.59.1 built with go1.22.3 from 1a55854a on 2024-06-09T18:08:33Z
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
@heyzling thanks for opening the issue and contributing the PR!
