### ISSUE TITLE
Pulumi-Terraform Bridge code has been moved to a new repo. 

### ISSUE THREAD

**Issue by axblum** [pulumi/pulumi-tf-provider-boilerplate#17]
After this Commit https://github.com/pulumi/pulumi-terraform/commit/286d9abc68557f4e722039d4b2e7c15e5df10690 The boilerplate code no longer seems to work as expected. Can this repo be updated to take advantage of the pulumi-terraform-bridge

**Comment by stack72** [comment]
@axblum apologies here - I will take care of this immediately
