### ISSUE TITLE
Will not work with go 1.13.x

### ISSUE THREAD

**Issue by yspotts** [pulumi/pulumi-tf-provider-boilerplate#20]
Might be worthwhile to add a note to the readme that the instructions WILL NOT work with go version 1.13.x. I know there is a note about pinning the travis build, but it is not clear that development will work with any other version. I had to downgrade to version 1.12 after much trial and error.

**Comment by stack72** [comment]
Hi @yspotts 

I will get this upgraded tonight

Sorry about this

Paul

**Comment by stack72** [comment]
Hi @yspotts 

I believe this will now work for you now - if you have any issues, please can you list them here with the error that you are seeing? I am not able to reproduce any failures now

Paul

**Comment by yspotts** [comment]
@stack72 thank you so much for the quick turnaround. 

Unfortunately, running the commands exactly as presented on the website, I am getting this error in the `make ensure` step:

```GO111MODULE=on GOPROXY='https://proxy.golang.org' go mod vendor
go: downloading github.com/hashicorp/vault v0.10.4
go: extracting github.com/hashicorp/vault v0.10.4
github.com/pulumi/pulumi-keycloak/examples tested by
	github.com/pulumi/pulumi-keycloak/examples.test imports
	github.com/pulumi/pulumi/pkg/testing/integration imports
	github.com/pulumi/pulumi/pkg/resource/stack imports
	github.com/pulumi/pulumi/pkg/secrets/cloud imports
	gocloud.dev/secrets/hashivault imports
	github.com/hashicorp/vault/api: ambiguous import: found github.com/hashicorp/vault/api in multiple modules:
	github.com/hashicorp/vault v0.10.4 (/Users/yoelspotts/go/pkg/mod/github.com/hashicorp/vault@v0.10.4/api)
	github.com/hashicorp/vault/api v1.0.5-0.20190909201928-35325e2c3262 (/Users/yoelspotts/go/pkg/mod/github.com/hashicorp/vault/api@v1.0.5-0.20190909201928-35325e2c3262)
```

I am running `go version 1.13.4`

For reference I am trying to create a pulumi package for keycloak based on: 
https://github.com/mrparkers/terraform-provider-keycloak

Thanks!

**Comment by stack72** [comment]
Hi @yspotts 

This is a provider specific issue - you will need to add this to the replace section of go.mod

```
github.com/hashicorp/vault => github.com/hashicorp/vault v1.2.0
```

**Comment by yspotts** [comment]
@stack72 thank so much for your help! that worked. You've been very helpful so I hesitate to push further, but hoping you might be able to help me solve my next issue. I'm a newbie to go, so its been a struggle. 

The keycloak provider references the schema in `github.com/hashicorp/terraform/helper/schema`. However, this boilerplate make use of `github.com/hashicorp/terraform-plugin-sdk/helper/schema` which I would assume is newer. Is there any way to coerce the "old" schema reference into the "newer" schema reference?

Thanks!!

**Comment by stack72** [comment]
ah!! It's one of those providers

You need to change the provider in the following places:

* https://github.com/pulumi/pulumi-vsphere/blob/master/cmd/pulumi-resource-vsphere/main.go#L18
* https://github.com/pulumi/pulumi-vsphere/blob/master/cmd/pulumi-tfgen-vsphere/main.go#L18
* https://github.com/pulumi/pulumi-vsphere/blob/master/resources.go#L6
* https://github.com/pulumi/pulumi-vsphere/blob/master/resources.go#L7

You then need to make some changes in your go.mod

This 

github.com/pulumi/pulumi-terraform v0.18.4-0.20191202134852-87cfb4dc8ae1

instead of pulumi-terraform-bridge

and you might need this entire *replace* section

```
replace (
	github.com/Azure/azure-sdk-for-go => github.com/Azure/azure-sdk-for-go v31.1.0+incompatible
	github.com/Azure/go-autorest => github.com/Azure/go-autorest v12.4.3+incompatible
	github.com/Nvveen/Gotty => github.com/ijc25/Gotty v0.0.0-20170406111628-a8b993ba6abd
	github.com/Sirupsen/logrus => github.com/sirupsen/logrus v1.4.2-0.20190403091019-9b3cdde74fbe
	github.com/golang/glog => github.com/pulumi/glog v0.0.0-20180820174630-7eaa6ffb71e4
	github.com/hashicorp/vault => github.com/hashicorp/vault v1.2.0
)
```

**Comment by yspotts** [comment]
Oh wow. Looks like I've got my work cut out for me.

So to be clear I need to change the provider itself in the places your
cited.

And then make a change to the go.mod in the provider or in the cloned
boilerplate?

Thanks so much for your help @stack72!

**Comment by stack72** [comment]
you can make all these changes in your copy of the boilerplate. The boilerplate has been set to work with the new terraform-plugin-sdk providers

If you push your code to github and link me, I can send you a PR if you want :)

**Comment by yspotts** [comment]
@stack72 you are too kind!

I sent you a link - https://github.com/yspotts/pulumi-keycloak

**Comment by stack72** [comment]
Hi @yspotts 

Now that the xmas break is over - I have sent a PR back to your repo :)

P.
