### ISSUE TITLE
Add the "Template repository" option to this repo

### ISSUE THREAD

**Issue by LouisAmon** [pulumi/pulumi-tf-provider-boilerplate#22]
Setting this repo as template repository allows users to create a new repository from it without using fork mechanisms (and having a dependency towards this repo)

See image below:
![image](https://user-images.githubusercontent.com/6024791/72068340-1fc31680-32e5-11ea-82a3-ea90b121ea1c.png)

Documentation:
- https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository
- https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template

**Comment by stack72** [comment]
Hi @LouisAmon 

great idea - I just enabled this for the repository now :)
