### ISSUE TITLE
Need help creating a pulumi-akamai package

### ISSUE THREAD

**Issue by yliu-d** [pulumi/pulumi-tf-provider-boilerplate#23]
Hi,

We want to use pulumi to configure Akamai CDN but they only have a terraform provider, hence I spent some time and created a `pulumi-akamai` package: https://github.com/yliu-d/pulumi-akamai

However, there are some build issues I couldn't figure out how to resolve, it looks like the Makefile only works with the CI/CD pipeline in the pulumi organization. One issue is somehow `GOPATH` is not in `PATH` even if I set it in the command line, hence I have to modify the Makefile to call the tfgen command. Another issue is somehow the typescript codegen is missing a closing brackets when it generates data resources. I used https://github.com/yliu-d/pulumi-akamai/commit/aeb5ad3f17be443dd41379cce493bf669807b97e to temporarily fix this issue for me.

Do you guys want to maintain this package in your organization so that the package can be built through your CI/CD pipeline and get released like usual pulumi providers?

Thanks!

**Comment by stack72** [comment]
Hi @yliu-d 

You can contact me on our community slack as stack72 or via email stack72 at Pulumi.com and we can talk about this

Hope this is ok?

Pail

**Comment by stack72** [comment]
This can be closed out as we have released this provider
