### ISSUE TITLE
Document how to build a community provider

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-tf-provider-boilerplate#28]
Until we have a better place to put it, we should create a docs directory that better outlines the process of how to use this repo. We can move it to its new home (wherever that may be) in the future.

**Comment by alexeyzimarev** [comment]
That would be really helpful. After some struggle, I managed to build a provider for Event Store Cloud, but I have no idea what to do next. How can I test it? All Pulumi providers must be in the Pulumi GitHub org, what is the process for submission? Is it possible to test the provider locally or instruct Pulumi CLI to get the provider from my own repo?

**Comment by AdamWorley** [comment]
I'm in a similar situation as @alexeyzimarev, I feel like it'd be great to get a few more providers from TF over to pulumi and this template project seems like it's really helpful to be able to that. 

Have there been any changes or has the new process been created somewhere else?

**Comment by guineveresaenger** [comment]
Hi all - we hope that the current shape of the README is more helpful on getting the community started, better than it was at last comment. Follow guidelines outlining "third-party" providers.

Please continue to open issues and check back for updates if we're missing things. ❤️

**Comment by guineveresaenger** [comment]
Fixed in #69
