### ISSUE TITLE
cannot find module providing package github.com/pulumi/pulumi/sdk/v2/go/common/util/buildutil

### ISSUE THREAD

**Issue by kaliumxyz** [pulumi/pulumi-tf-provider-boilerplate#31]
when following the instructions at the second step:
> make prepare NAME=foo REPOSITORY=github.com/pulumi/pulumi-foo
I get the following error as part of the output:
> scripts/get-py-version.go:7:2: cannot find module providing package github.com/pulumi/pulumi/sdk/v2/go/common/util/buildutil: working directory is not part of a module

It seems that the build output is correct, the get-py-version.go script just doesn't seem to run without affecting the resulting build.

**Comment by jaxxstorm** [comment]
@kaliumxyz which `Go` version are you running?

**Comment by kaliumxyz** [comment]
I'm running `Go` `1.14.1`

**Comment by jaxxstorm** [comment]
We spoke about this in slack, currently `go1.13` is primarily used across Pulumi and because there's no `go.mod` in the root directory, `go1.14` doesn't seem to work with this script.

A quick fix is to modify the `Makefile` to update the `PYPI_VERSION` variable:

```
PYPI_VERSION    := $(shell (cd scripts && ./get-py-version))
```
