### ISSUE TITLE
[Makefile] install_plugins:: installing non-existent plugin

### ISSUE THREAD

**Issue by iridian-ks** [pulumi/pulumi-tf-provider-boilerplate#37]
I'm trying to create my own provider from a Terraform provider. I followed the README.md and noticed this immediately fails on the first step.

```
 83 install_plugins::
 84         [ -x $(shell which pulumi) ] || curl -fsSL https://get.pulumi.com | sh
 85         pulumi plugin install resource $(PACK) $(PROVIDER_VERSION)
```

I guess my understanding was this repo was meant for creating/developing a new provider. Why would this attempt to pull a provider from Pulumi instead of installing the provider that's currently being developed?

I noticed that there's the `-f` option to install from a tarball. Should this Makefile start by taring up the local provider and installing from that?

**Comment by stack72** [comment]
I’m about to open a PR that removes it completely! :)
