### ISSUE TITLE
unknown field 'AsyncDataSources' in struct literal of type tfbridge.JavaScriptInfo

### ISSUE THREAD

**Issue by donovanmuller** [pulumi/pulumi-tf-provider-boilerplate#39]
Running the `make` target results in the following error:

```console
$ make
================
xxx Package
================
BUILD:
[ -x /usr/local/bin/pulumi ] || curl -fsSL https://get.pulumi.com | sh
cd provider && go install -ldflags "-X github.com/pulumi/pulumi-xxx/provider/pkg/version.Version=v0.0.1-alpha.1593782371+g931a267.dirty" github.com/pulumi/pulumi-xxx/provider/cmd/pulumi-tfgen-xxx
# github.com/pulumi/pulumi-xxx/provider
./resources.go:132:4: unknown field 'AsyncDataSources' in struct literal of type tfbridge.JavaScriptInfo
make: *** [tfgen] Error 2
```

because

https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/931a2670ae5ec0bf2ff7ba80f05c862bcd3f651a/provider/resources.go#L132 references `AsyncDataSources` on `JavaScriptInfo` [struct](https://github.com/pulumi/pulumi-terraform-bridge/blob/9d79abaa24fee8c192bbd728f6e3b76d1ad3dabd/pkg/tfbridge/info.go#L270), which does not seem to exist.

**Comment by Kamaradeivanov** [comment]
Same issue for me with scaleway, a french cloud provider. You could try here : https://github.com/Kamaradeivanov/pulumi-scaleway

I tried to use go 1.13.8 and 1.14.2 but the last one seems to be incompatible because I got the following issue during `make ensure` command

```
go: github.com/pulumi/pulumi-terraform master => v3.3.0+incompatible
```

**Comment by Kamaradeivanov** [comment]
If I comment the line, i can go further, but I don't know if i'm missing something.
