### ISSUE TITLE
Installing a local python package

### ISSUE THREAD

**Issue by retr0h** [pulumi/pulumi-tf-provider-boilerplate#6]
I am using python 2.7 currently (working around #5).  I ran `make build` which results in a python package I can install.

When installing the python package, it fails a the end with:

```
    subprocess.CalledProcessError: Command '['pulumi', 'plugin', 'install', 'resource', 'digitalocean', '0.14.1-dev-1532403186-g5617bce-dirty']' returned non-zero exit status 255
```

It looks as though `pulumi plugin install resource` requires the plugin to be hosted by pulumi.  How can I install locally?  I would imagine when developing resources I would want to test locally before pushing.

**Comment by leezen** [comment]
You can choose to point to your own server, e.g. https://github.com/pulumi/pulumi/pull/2789
This is tracked in https://github.com/pulumi/pulumi/issues/3297 so closing as a dupe
