### ISSUE TITLE
Go compilation error when building a provider

### ISSUE THREAD

**Issue by itay** [pulumi/pulumi-tf-provider-boilerplate#60]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I don't have the exact repro for this, but when I cloned this repo (after creating my own from a template) and edited everything, there was a Go compilation error with the Pulumi Go library (due to a missing signature). My solution was to update the terraform bridge go module from 3.18.0 to 3.19.0, which seemed to fix it. My guess is this is due to updating to a newer version of the Pulumi SDK.

Sorry I don't have more information here.

### Steps to reproduce

See above.

**Comment by stack72** [comment]
Hi @itay do you have the error message you received?

**Comment by itay** [comment]
It occurred to me I can just change `go.mod` to point to 3.18 again to reproduce the error:

```
$ make tfgen
[ -x /Users/itay/.pulumi/bin/pulumi ] || curl -fsSL https://get.pulumi.com | sh
pulumi plugin install resource random 4.3.1
(cd provider && go build -o /Users/itay/work/okera/pulumi-frontegg/bin/pulumi-tfgen-frontegg -ldflags "-X github.com/okera/pulumi-frontegg/provider/pkg/version.Version=0.0.1+dirty" github.com/okera/pulumi-frontegg/provider/cmd/pulumi-tfgen-frontegg)
# github.com/pulumi/pulumi/pkg/v3/codegen/schema
../../../go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.23.2/codegen/schema/loader.go:120:30: not enough arguments in call to pkgPlugin.Install
	have (*os.File)
	want (io.ReadCloser, bool)
make: *** [tfgen] Error 2
```

This is fixed if I change:

```
github.com/pulumi/pulumi-terraform-bridge/v3 v3.18.0
```

to be `v3.19.0`

**Comment by stack72** [comment]
The deps have been updated and will be better kept up to date :) Sorry about this!

Paul
