### ISSUE TITLE
Mismatches in the files in `deployment-templates`

### ISSUE THREAD

**Issue by henriiik** [pulumi/pulumi-tf-provider-boilerplate#70]
### What happened?

I recently created a custom provider based on this template and i ran into a few issues.

## 1. Make command mismatch in `deployment-templates/.goreleaser.yml`

It is `build_provider`, but it should be `provider`.

https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/efb5bdb0aa7a6f5fad9555c98bd43fa700c21eee/deployment-templates/.goreleaser.yml#L6

https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/efb5bdb0aa7a6f5fad9555c98bd43fa700c21eee/Makefile#L55

## 2. Binary name mismatch in `deployment-templates/.goreleaser.yml`

It is `provider-xyz` but it should be `pulumi-resource-xyz`, the latter is the file name the pulumi plugin install command looks for.

https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/efb5bdb0aa7a6f5fad9555c98bd43fa700c21eee/deployment-templates/.goreleaser.yml#L8

https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/efb5bdb0aa7a6f5fad9555c98bd43fa700c21eee/deployment-templates/.goreleaser.yml#L22

## 3. Job name mismatch in `deployment-templates/release.yml`

There is a job named `publish-binary` but the other jobs have `needs: publish_binary` 

https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/efb5bdb0aa7a6f5fad9555c98bd43fa700c21eee/deployment-templates/release.yml#L32

https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/efb5bdb0aa7a6f5fad9555c98bd43fa700c21eee/deployment-templates/release.yml#L63

### Steps to reproduce

Copy the files in `deployment-templates` according to the readme and try to publish a release.

### Expected Behavior

A release should be published.

### Actual Behavior

Github actions will crash.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkisk** [comment]
Thank you so much, I'll get this fixed up!

**Comment by henriiik** [comment]
@jkisk thank you!
