### ISSUE TITLE
Community Providers: Make sure `pluginDownloadUrl` works as expected

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-tf-provider-boilerplate#74]
A community member was [reporting difficulty in using their wrapped TF provider](https://github.com/pulumi/pulumi/issues/9606#issuecomment-1137206046) via `pluginDownloadUrl`.

We should ensure that `pluginDownloadUrl` works correctly.

**Comment by ringods** [comment]
I think this is solved & documented now with support for Github releases, using the Github API:

https://www.pulumi.com/docs/guides/pulumi-packages/how-to-author/#support-for-github-releases

For Pulumiverse, I have documented how to configure both a native and a TF-bridged provider here:

https://github.com/pulumiverse/infra/blob/main/README.md#package-registries

**Comment by stack72** [comment]
This is indeed solved now
