### ISSUE TITLE
`make prepare` should also set `ORG`

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi-tf-provider-boilerplate#75]
It looks like currently, the `ORG` environment variable is [hard-coded as `pulumi`](https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/813f5f94d3804c3ce24fc91d4ce59b49d14f1f9d/Makefile#L5), which causes `make tfgen` to fail in ways that take a little while to figure out when you're targeting a GitHub org other than `pulumi`. We should mention that this can be set (perhaps optionally) and then use it in `make prepare`.

**Comment by stack72** [comment]
Hey @cnunciato 

We do actually call out that the org needs to be set:

```
Note for third-party providers:

Make sure to set the correct GitHub organization/username in all files referencing your provider as a dependency:
examples/go.mod
provider/resources.go
sdk/go.mod
provider/cmd/pulumi-resource-foo/main.go
provider/cmd/pulumi-tfgen-foo/main.go
```

This is as part of the https://github.com/pulumi/pulumi-tf-provider-boilerplate#creating-and-initializing-the-repository guide - we can make changes to the org BUT it's much more invasive as we can't blanket change `pulumi` to `myOrg` due to needing to bring in codegen dependencies

**Comment by cnunciato** [comment]
@stack72 Yep, I read that, and did make those changes, but `make tfgen` still failed until `ORG` was changed. Thanks for the explanation, though. Do you think it'd be better (for now) to mention having to make that change manually in the Makefile before running `make tfgen`?

**Comment by stack72** [comment]
Oooohhhhhhhh now I see what your issue calls out! I thought it was for an enhancement to make org work but it's about calling out that Org needs set in the makefile as well right?

**Comment by cnunciato** [comment]
That’s right yeah — it’s just that that one Makefile variable, `ORG`, needs to be changed from `pulumi` to your org name before you can run `make tfgen`. (IIRC it’s the same thing you and David ran into in https://m.youtube.com/watch?v=ZjTFaqMrYvY with ConfigCat.)

**Comment by gpduck** [comment]
I have some updates to the makefile that automate changing the publisher/org as well as updating the go module import statements, would you be interested in me submitting a PR with those changes?

**Comment by cnunciato** [comment]
@gpduck Yes, we definitely would! Thanks in advance!
