### ISSUE TITLE
Makefile should include build targets for plugins for multiple platforms

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-tf-provider-boilerplate#80]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently `make provider` in the Makefile only builds for the architecture the user is building the provider on.
The Makefile should include targets for the standard platforms, such as:

- Mac AMD64
- Mac M1/2
- Linux AMD64
- Linux M1/2
- Windows AMD64

This way folks who are new to go in general and bridging providers specifically will know how to build for the platform(s) they want to use and save time figuring out why a plugin doesn't work.

**Comment by stack72** [comment]
Hey @MitchellGerdisch 

We actually do have a goreleaser template in the repo already that does this for the user - https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/main/deployment-templates/.goreleaser.yml

We tend to not have any GOOS / GOARCH in any of our builds scripts that are go based binaries

I hope this helps

Paul

**Comment by MitchellGerdisch** [comment]
Can the readme (https://github.com/pulumi/pulumi-tf-provider-boilerplate#adding-mappings-building-the-provider-and-sdks) include instructions on how to create the cross-compiled plugins, then?
The root issue I'm hoping we can address is for the person who is not very go-savvy or bulid-savvy but able to make their way through the bridging process and who needs to produce plugins for different architectures. So, they may not know to look for the goreleaser stuff or how it all works even if they find it. So I think including at least some pointers/instructions to help this person  would be useful.

**Comment by stack72** [comment]
@MitchellGerdisch I am honestly not sure we should do this - none of our tooling talks about cross compilation. It would be us documenting go build commands and setting variables for GOOS and ARCH. We could link to the goreleaser docs if you feel that's important? We (within Pulumi) don't ever run anything other than goreleaser build command - do we really expect users to be able to cross compile locally?
