### ISSUE TITLE
Error on Unshallow clone for tags - github action step

### ISSUE THREAD

**Issue by ar4mirez** [pulumi/pulumi-tf-provider-boilerplate#81]
Is anyone else having this error?

```shell
 ! [rejected]        v0.0.1-alpha.1658405904     -> v0.0.1-alpha.1658405904  (would clobber existing tag)
```
The fix is pretty easy by adding a `-f` flag, but I want to know if is just me.
https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/8a52b964412f450a8418c3d1b53f923df6f9a62a/deployment-templates/release.yml#L39

Best,

**Comment by stack72** [comment]
Hi @ar4mirez 

I am sorry you are hitting this issue - we tend to not create tags for dev builds so I think this could be the problem. I worry that adding -f to our template may cause others issues but I suggest if you need it to add it :)

Paul

**Comment by ar4mirez** [comment]
@stack72 thanks for the reply. Just to clarify what you mean is that usually the tags for release does not contain the `-alpha.[BUILD_NUMBER]`? Am I right?

**Comment by stack72** [comment]
exactly that - those are the default branch build ids only - we (internally at Pulumi) only suggest to push tags when making a release e.g. v0.0.1-rc.1 etc

**Comment by ar4mirez** [comment]
@stack72 gotcha, sorry to bother one more question, what is not clear to me is how `pulumictl version` always include the build number, I was able to remove the hash with `-o` but always keep the build number am I missing something here? I'm trying to find an standard/best practice way to publish the sdks.

Btw I'm using pulumiverse/astra as guide.
