### ISSUE TITLE
Can this repo support wraps the Terraform provider builded by terraform-plugin-framework

### ISSUE THREAD

**Issue by shiyuhang0** [pulumi/pulumi-tf-provider-boilerplate#90]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Can this repo support wraps the Terraform provider builded by terraform-plugin-framework?

**Comment by stack72** [comment]
Hi @shiyuhang0 

This is something we will look at adding soon - the plugin-framework has been starting to get some traction

Paul

**Comment by shiyuhang0** [comment]
I suggest stating in the README.md that terraform-plugin-framework is not supported to reduce unnecessary attempts

**Comment by oun** [comment]
Do you have plan to support terraform plugin framework?

**Comment by ericrudder** [comment]
You can follow our overall progress at:
https://github.com/pulumi/pulumi-terraform-bridge/issues/744

Also note the community slack link mentioned there if you'd like more
frequent updates!
