### ISSUE TITLE
Typo in deployment-templates/release.yml template

### ISSUE THREAD

**Issue by ocobleseqx** [pulumi/pulumi-tf-provider-boilerplate#94]
Hi, I just found a small typo in the release.yml template

https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/2f2b03c62f79dee5d1f8f4a84d3c9f651ec22720/deployment-templates/release.yml#L87

Should be dotnetvers**i**on

```
dotnet-version: ${{matrix.dotnetversion}} 
```

to match

https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/2f2b03c62f79dee5d1f8f4a84d3c9f651ec22720/deployment-templates/release.yml#L124

**Comment by jazzyfresh** [comment]
Thank you for reporting this and for making a Pulumi provider! 

I created a pull request with a fix (https://github.com/pulumi/pulumi-tf-provider-boilerplate/pull/96). I also filed another ticket (https://github.com/pulumi/ci-mgmt/issues/368) to make sure this boilerplate project benefits from the latest improvements via our provider update automation system.

**Comment by ericrudder** [comment]
note that i already did this in
https://github.com/pulumi/pulumi-tf-provider-boilerplate/tree/ericrudder-patch-1
